version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: development
  reviewers:
  - echarrod
  - gautam-yoti
  assignees:
  - echarrod
