language: python

dist: xenial

git:
  depth: false

jobs:
  allow_failures:
    - python: "3.8-dev"
  include:
    - &test
      stage: Test
      python: "3.6"
      cache: pip
      before_install:
        - pip install -U setuptools
      install:
        - pip install -r requirements.txt
        - pip install -e .[dev]
      script:
        - py.test -v
    - <<: *test
      python: "3.6-dev"
    - <<: *test
      python: "3.7"
    - <<: *test
      python: "3.7-dev"
    - <<: *test
      python: "3.8"
    - <<: *test
      python: "3.8-dev"
